module.exports = {
  testMatch: ["**/__tests__/**/*_test.bs.js"],
  moduleFileExtensions: ["js"],
  transform: {
    "^.+\\.js$": "babel-jest",
  },
  transformIgnorePatterns: [
    // transform ES6 modules generated by BuckleScript
    // https://regexr.com/46984
    "/node_modules/(?!(@.*/)?(bs-.*|reason-.*|react-syntax-highlighter)/).+\\.js$",
  ],
};
